---
title: "Contents"
pagetitle: "RaukR 2025 • Contents"
description: "Course materials including presentations (slides) and practical exercises (labs)"
toc: false
date: ""
sidebar: false
format:
  html:
    number-sections: false
execute:
  freeze: false
---

:::{.contents-table .column-body-outset}

|Topic                                  |Presenter                              |Links|
|---------------------------------------|---------------------------------------|-----|
|[WEEK 1]{.badge .badge-primary}                                          |||
|[09-Jun-2025 (Mon)]{.badge .badge-secondary}                               |||
|Welcome                                |Marcin Kierczak, Sebastian DiLorenzo   |[Slides](slides/welcome/index.html)|
|Best Coding Practices in R             |Sebastian DiLorenzo           |[Slides](slides/coding/index.html), [Lab](labs/coding/index.html)|
|Project environments using Renv        |Roy Francis                   |[Slides](slides/r-env/index.html)|
|Debugging, Profiling and Optimization  |Marcin Kierczak               |[Slides](slides/debugging/index.html), [Lab](labs/debugging/index.html)|
|[10-Jun-2025 (Tue)]{.badge .badge-secondary}                          |||
|Introduction to Quarto                 |Christophe Dervieux           |[Slides](https://cderv.github.io/raukr-2025-quarto/)|
|Literate programming with Quarto       |Roy Francis                   |[Lab](labs/quarto/index.html)|
|Creating websites with Quarto          |Roy Francis                   |[Lab](labs/quarto-site/index.html)|
|Functions & Scripts                    |Sebastian DiLorenzo           |[Slides](slides/scripting/index.html), [Lab](labs/scripting/index.html)|
|R & AI                                 |Sebastian DiLorenzo           |[Slides](slides/ai/index.html)|
|[11-Jun-2025 (Wed)]{.badge .badge-secondary}                               |||
|Positron                               |Jenny Bryan                          |[pos.it/ron-raukr](https://pos.it/ron-raukr)|
|Plotting with ggplot2                  |Roy Francis                            |[Slides](slides/ggplot/index.html), [Lab](labs/ggplot/index.html)|
|[12-Jun-2025 (Thu)]{.badge .badge-secondary}                               |||
|Tidyverse                              |Marcin Kierczak               |[Slides](slides/tidyverse/index.html), [Lab](labs/tidyverse/index.html)|
|Futurverse                             |Henrik Bengtsson, UCSF                 ||
|[13-Jun-2025 (Fri)]{.badge .badge-secondary}                               |||
|R Packages                             |Jenny Bryan, Posit                     ||
|reticulate: Combining R with Python    |Nina Norgren                           |[Slides](slides/reticulate/index.html), [Lab](labs/reticulate/index.html)|
|[WEEK 2]{.badge .badge-primary}                                          |||
|[16-Jun-2025 (Mon)]{.badge .badge-secondary}                               |||
|Statistics and machine learning in R   |Nikolay Oskolkov                       |[Slides](slides/ml/index.html), [Lab](labs/ml/index.html)|
|Object-oriented programming            |Marcin Kierczak                        |[Slides](slides/oop/index.html), [Lab](labs/oop/index.html)|
|[17-Jun-2025 (Tue)]{.badge .badge-secondary}                               |||
|Web apps with Shiny                    |Roy Francis                            |[Slides](slides/shiny/index.html), [Lab](labs/shiny/index.html)|
|Projects                               |Guilherme Dias                         |[Lab](labs/projects/index.html)|
:::

<br>

[[Slides {{< fa circle-chevron-right >}}]{.btn .btn-sm .btn-primary}](slides/index.html) [[Labs {{< fa circle-chevron-right >}}]{.btn .btn-sm .btn-primary}](labs/index.html) 
